### ISSUE TITLE
Fully working but i've some questions

### ISSUE THREAD

**Issue by adorest** [visibait/VB-AC#10]
Thankyou so much for realese this AC, i’ve been waiting a thread like this for a long time.
You’re really helped so many newbie Developers like me, thankyou so much!

but i’ve some problems, it’s randomly get banned because of this :
[here](https://i.imgur.com/9IkaYfg.png)
and i can't open admin menu with /vbacmenu or press INSERT, i've following all the step on readme files but still can't open the menu.

how can i fix this?

**Comment by visibait** [comment]
fixed.
