### ISSUE TITLE
AntiVehicleSpawn when you buy a car

### ISSUE THREAD

**Issue by giannis97** [visibait/VB-AC#12]
how i can fix when you buy the car from cardealer it get banned with this reason

AntiVehicleSpawn

**Comment by visibait** [comment]
Just put the cardealer spawn car coords in the client_config.lua and that's it 
VB_AC.GarageList = { -- Place the car dealer coords right here
	{x = 217.89, y = -804.99, z = 30.91}, -- Example
}

**Comment by mahanmoulaei** [comment]
I have a housing system that spawns player cars next to their owned home.
Do I have to add all of the house's coordinates to VB_AC.GarageList or is there any other workaround for this?
Cuz in that case, I have to add lots of vector3 to the config file....

**Comment by visibait** [comment]
Yep, you have to add all the vectors to the config or disable the anti vehiclespawn function

**Comment by giannis97** [comment]
alright i am gonna try this, also how to change the menuv open button? because i have another menu at INS button
also if you try to open it you have to restart anticheat many times to make menuv work why?

**Comment by visibait** [comment]
> alright i am gonna try this, also how to change the menuv open button? because i have another menu at INS button
> also if you try to open it you have to restart anticheat many times to make menuv work why?

Fixed in the new anticheat version, download it and check if everything works.
