### ISSUE TITLE
Not sure what this means?

### ISSUE THREAD

**Issue by JohnnyS** [visibait/VB-AC#14]
SCRIPT ERROR: @VB-AC/server/main.lua:78: attempt to index a nil value (local '_tchar')

Getting that in the console not sure what happened exactly. Was just standing and got banned for revive

**Comment by JohnnyS** [comment]
![image](https://user-images.githubusercontent.com/62607662/116951856-0458e900-ac57-11eb-8fde-ab46280c718b.png)

Also How to make it where it kicks only and not auto ban? I removed the ban function but errors pop up in the console. Was there something I missed?

**Comment by visibait** [comment]
There's a new update, check it and disable VB_AC.BanPlayers in the Config
