### ISSUE TITLE
Possible misstype? 

### ISSUE THREAD

**Issue by Nixtl** [visibait/VB-AC#17]
So when I installed the menu and everything, attempting to open the menu resulted in this error: 
![image](https://user-images.githubusercontent.com/43684027/117512407-90238b80-af5d-11eb-8c92-dfda9b0b6655.png)
changing this: 
![image](https://user-images.githubusercontent.com/43684027/117512471-acbfc380-af5d-11eb-9565-70a0b9d88674.png)
to this:
![image](https://user-images.githubusercontent.com/43684027/117512508-c2cd8400-af5d-11eb-85f4-ebf4aed2d7c2.png)
fixes the issue entirely and other then that I have no other issues. 

I see that line was changed in v2.0 to v2.1, could be done on purpose, could be a accident, I don't know I just know until I changed that line the menu refused to work and it could be a possible problem for others. Figured I'd say something.

**Comment by visibait** [comment]
Yep, it was a mistype... I fixed it rn :)
