### ISSUE TITLE
detection

### ISSUE THREAD

**Issue by wanda321** [visibait/VB-AC#18]
this anticheat does not detect v0.3 wavecheat menu [free]

source code:
https://ghostbin.com/paste/Xqggg

**Comment by visibait** [comment]
I'll patch that menu in a few hours and I'll make some optimizations to the anticheat. Thanks for reporting the issue :)

**Comment by visibait** [comment]
Menu Patched, uninstall the old AC version using vbacuninstall and download and install the new version.
