### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by JohnnyS** [visibait/VB-AC#19]
I am getting these errors in the console

SCRIPT ERROR: @VB-AC/server/main.lua:16: attempt to index a nil value (local '_char')
SCRIPT ERROR: @VB-AC/server/main.lua:30: attempt to compare nil with number

It looks like it is still working but not sure why but maybe believed to be something with the money check?

**Comment by visibait** [comment]
Hey, download the new version released in my repository and check if works.

**Comment by JohnnyS** [comment]
> Hey, download the new version released in my repository and check if works.

No that did not work also did you get around to if the blacklist vehicle spawns in it doesnt spawn in fully?

**Comment by JohnnyS** [comment]
SCRIPT ERROR: @VB-AC/server/main.lua:30: attempt to compare nil with number

This error pops up still

**Comment by JohnnyS** [comment]
Injection detected in resource: esx_PawnShop Type: CKgangisontop

Getting this too in logs but unsure where to start to start troubleshooting it. multiple other scripts has same thing

**Comment by visibait** [comment]
> Injection detected in resource: esx_PawnShop Type: CKgangisontop
> 
> Getting this too in logs but unsure where to start to start troubleshooting it. multiple other scripts has same thing

You have to get in the Anti-Injection file generated in that resource and remove all the lines that contain "CKgangisontop"

**Comment by JohnnyS** [comment]
> > Injection detected in resource: esx_PawnShop Type: CKgangisontop
> > Getting this too in logs but unsure where to start to start troubleshooting it. multiple other scripts has same thing
> 
> You have to get in the Anti-Injection file generated in that resource and remove all the lines that contain "CKgangisontop"

Thats a lot of resources then I will have to go through lol the orig error is still showing unless i put the money check to false then it goes away
