### ISSUE TITLE
How do I turn off other admin accesses and open the admin menu?

### ISSUE THREAD

**Issue by twitoorel1** [visibait/VB-AC#23]
How do I turn off other admin accesses and open the admin menu?

**Comment by visibait** [comment]
I'm working on that. If you want, you can test the new AC  version located in the DEV branch, but I'm not sure if it works fully....

**Comment by twitoorel1** [comment]
If I cancel the menu will it hurt my anti-cheat?

**Comment by visibait** [comment]
I don't think so, you can try if u want.

**Comment by visibait** [comment]
I have released a new anticheat update in the dev branch, I've tested it a little bit and it's working fine, if you want you can try it to see if works. In that update you're now able to bypass some admins but not allowing them to open the menu
