### ISSUE TITLE
[Bug] Mass Citizen.Invoke

### ISSUE THREAD

**Issue by laggis** [visibait/VB-AC#24]
Hey so my player getting banned when they are point and getting this ban massage "screenshot show" i have turn off anti injecting and it still bans ppl any way to turn this off? otherwise i have no problem the anti cheat then this part

Edit this massage only comes up when you pointing with B 
![Untitled](https://user-images.githubusercontent.com/18127838/118055309-286ba700-b388-11eb-8306-0edd147dc06f.png)

**Comment by wanda321** [comment]
i think you need to separate scripts individually, not several scripts combined into one

**Comment by laggis** [comment]
> i think you need to separate scripts individually, not several scripts combined into one

That sounds bad that i have to do that but you might have right

**Comment by visibait** [comment]
Hey! There's an easy fix on that.

**Comment by visibait** [comment]
Get in the scrp-scripts resource and you'll find a file with random letters (UIDkdDAdkd for example.) Get inside that file and you'll find some lines like this at the end of the file: https://imgur.com/7JVmT52

You have to change the number (in my case is 3000) for something higher, like 5000, then restart your server.

**Comment by laggis** [comment]
Thx that was actually pretty easy haha
