### ISSUE TITLE
Error in F8 console

### ISSUE THREAD

**Issue by JohnnyS** [visibait/VB-AC#26]
![image](https://user-images.githubusercontent.com/62607662/118209983-b3f04100-b437-11eb-866b-45bcb39a47fe.png)

Getting these errors in the console but I think it works fine

**Comment by visibait** [comment]
Can you open the admin menu?

**Comment by JohnnyS** [comment]
Not at all I am not sure as well if I am using the right ID too I did the same format but it wouldnt let me.
