### ISSUE TITLE
Script error spam in console after updating to 3.0

### ISSUE THREAD

**Issue by mavroses** [visibait/VB-AC#27]
![ff6e1320b0a749ef98631a3d938e230a](https://user-images.githubusercontent.com/62800330/118252627-43820800-b4a9-11eb-9feb-b6315f2ae785.png)

**Comment by visibait** [comment]
Fixed! Download the new version.

**Comment by mavroses** [comment]
Did and it fixed it but now it does this.
![9cfa6e6730ad201faafa1e654bb79ceb](https://user-images.githubusercontent.com/62800330/118282738-e7ca7580-b4ce-11eb-9de5-c13dc56d3481.png)

**Comment by visibait** [comment]
Download the new version and tell me if works :)
