### ISSUE TITLE
bug command vbacinstall

### ISSUE THREAD

**Issue by Aysmow** [visibait/VB-AC#33]
**When I make the commands for anti injection it doesn't work, it doesn't bother me** 
![image](https://user-images.githubusercontent.com/74377244/119135774-25834d00-ba3f-11eb-98e2-2c7c235bdfa1.png)

**Comment by visibait** [comment]
Hey, have you started the resource in the server.cfg? Do you get any script errors if you restart the script?

**Comment by Aysmow** [comment]
I started well is no error

**Comment by phyroxneyver** [comment]
alguien sabe como puedo solucionar esto?[https://i.imgur.com/mmFy2Ii.jpg](url)

**Comment by phyroxneyver** [comment]
![Captura de pantalla (181)](https://user-images.githubusercontent.com/84684956/119276478-797d6580-bbe8-11eb-974b-ddf5c8247596.jpg)
como soluciono este error?
