### ISSUE TITLE
error server/main.lua:30 - 16

### ISSUE THREAD

**Issue by phyroxneyver** [visibait/VB-AC#35]
![Captura de pantalla (181)](https://user-images.githubusercontent.com/84684956/119276511-9fa30580-bbe8-11eb-98dc-bcc67a785fd6.jpg)
tengo un problema con el anticheat me aparece este error puedes decirme si es normal o que hay q solucionarlo?

**Comment by visibait** [comment]
Hay que arreglarlo, si le encuentras tu la forma hazlo, de todas formas voy a reescribir el anticheat arreglando todo eso.
