### ISSUE TITLE
[FEATURE REQUEST] Requesting a Delete All Nearby Vehicles

### ISSUE THREAD

**Issue by JohnnyS** [visibait/VB-AC#38]
In the menu instead of delete all vehicles can we get a delete all nearby and not player owned only npc vehicles?

**Comment by visibait** [comment]
Hmmm nice idea, I'll probably implement this in future updates. Btw there are some scripts that already do that job (https://forum.cfx.re/t/release-delete-vehicle-script-v1-1-0-updated-2020/7727)
