### ISSUE TITLE
Injections concern

### ISSUE THREAD

**Issue by JohnnyS** [visibait/VB-AC#40]
Some injection detections seem to spam the logs and how do I turn these off or adjust them. These are legit players popping up in the log.

Ex:
Injection detected in resource: trew_hud_ui Type: SetPedConfigFlag Detected. Args: 32 true

Injection detected in resource: bob74_ipl Type: DrawRect Function Detected

Injection detected in resource: dpemotes Type: RequestScaleformMovie Function Detected (Possible Menu)

Injection detected in resource: wk_wars2x Type: Print Function Detected. Text Printed: [Wraith ARS 2X]: Could not find any saved operator menu data.

Injection detected in resource: krz_personalmenu-2.0 Type: RequestScaleformMovie Function Detected (Possible Menu)

and so on

**Comment by visibait** [comment]
Hey! I suppose that you've installed Anti Injection. You can easily fix that by getting in the files generated by the anticheat in each resource (8uisd9f9asfdf.lua) and remove everything that checks for that type of natives. If you can't get it working, you can also send that resources to me and I'll fix them for you (https://discord.gg/RaRZNE6a)
