### ISSUE TITLE
one last hack problem

### ISSUE THREAD

**Issue by zoomlordir** [visibait/VB-AC#42]
hi , thanks for responding
i invited alot of hackers to my server for checking all feature of hackers and AC works good but only one hack still work
i dont know what is that but keep tasing all players inside server realy like ragdoll 
can you help me about that?

**Comment by visibait** [comment]
Hey! Have you tested the dev version? It should patch more menus.

**Comment by zoomlordir** [comment]
yes but not working for me 
logs without names or steamid
make players ping high
and ... i cant even connect to the server

**Comment by zoomlordir** [comment]
and last time i saw a hacker spawn object (police box object) inside or top of players 
object move with player 
that's realy bad cuz we have to restart the server
do you know some script or anything to remove objects with command?

**Comment by visibait** [comment]
The menu has a "delete all props option", but btw the anticheat doesn't allow to spawn props that aren't whitelisted... Also it ratelimits the amount of props a user can spawn, if it exceeds the limit the props just get deleted.

**Comment by zoomlordir** [comment]
that's new hack it will spawn object inside players even blacklist vehicles or props 
AC working for spamming vehicles or props but not for this hack
can you find a solution for this?
thank you

**Comment by visibait** [comment]
working on it (next update)
