### ISSUE TITLE
Fps problems

### ISSUE THREAD

**Issue by RAXIC55** [visibait/VB-AC#44]
I installed vbac system on my server but there are serious fps losses please fix
Server features : 
16 gb ram 200gb m2 ssd E5 2697 v2 10 core

**Comment by zoomlordir** [comment]
wow mine is 4gb ram 2core cpu and i dont have fps problem
check your resources

**Comment by Heavybob** [comment]
How many players are on your server?

**Comment by RAXIC55** [comment]
> 
> 
> How many players are on your server?

Average 25 30

**Comment by RAXIC55** [comment]
> 
> 
> wow mine is 4gb ram 2core cpu and i dont have fps problem
> check your resources

Could the cause be a conflict with a script? ?

**Comment by visibait** [comment]
It could be a conflict with a script. You can try to download the dev version and see if works, that one is pretty well optimized server side and client side (~0.01-0.02)
