### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by zoomlordir** [visibait/VB-AC#47]
hi again i need help 
i cant find name of this hash -434007626 AC ban players for spawning this can you send the name or can i put hash for whitelisted props?
and i cant open menuv can you explain how it work? and how can i change the keybind for menu
thanks

**Comment by zoomlordir** [comment]
> probably some custom entity, just whitelist it?

yes can you tell me the name of this object? i have to whitelist it
`-434007626`

**Comment by iSentrie** [comment]
i cant cus its **custom** probably

**Comment by zoomlordir** [comment]
can i put hash key in whitelist? 
how can i find custom prop name by hash?

**Comment by iSentrie** [comment]
> can i put hash key in whitelist?
yes, probably
> how can i find custom prop name by hash?
you cant
