### ISSUE TITLE
Banned by resource: monitor

### ISSUE THREAD

**Issue by SeaLife** [visibait/VB-AC#48]
**Problem**

All Users joining (non-admins) are getting banned for:

```
Injection detected in resource: monitor Type: RequestScaleformMovie Function Detected (Possible Menu)
```

Can i somehow disable this?

**Comment by Jarynnnn** [comment]
Go to `client_config.lua` and change `VB_AC.AntiCommandInjection` to false.

**Comment by SeaLife** [comment]
Hey, thanks for your response..

The value is already `false` (Is false by default i guess)

**Comment by booyodlism** [comment]
try to disable on artifact folder "citizen\system_resources\monitor", i had this problem before, but now it already no problem.

**Comment by BunnyFunner** [comment]
Go to ur SQL where it's the bans and delete all, if that doesn't do anything DM me ! Bunny ™#1337

**Comment by BunnyFunner** [comment]
If there are STAFF members put he hex in the CFG with/without the MENU

**Comment by SeaLife** [comment]
> try to disable on artifact folder "citizen\system_resources\monitor", i had this problem before, but now it already no problem.

Hey, where do i find this folder? I dont have a `citizen` directory on my server..
It cant be found unter `resources`
And there is only a `txData` and a `alpine`-directory

For reference: im using Linux

@BunnyFunner i disabled Bans bec. we'r still in development phase, so no one was actually banned but the discord hook triggers

**Comment by BunnyFunner** [comment]
But was Ur problem? Explain pls

**Comment by SeaLife** [comment]
@BunnyFunner if a non-admin joins the server, the VB-AC tries to ban them for the reason i posted above.

VB-AC dont actually bans them yet on my server, because i disabled the banning feature, but as soon as i will go live with the server, it will be enabled.

**Comment by BunnyFunner** [comment]
Maybe it isn't a thing of the AC, maybe it's a thing of Ur server

**Comment by visibait** [comment]
Upload the new version .
