### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by zoomlordir** [visibait/VB-AC#54]
nice Release so many problems fixed i have 2 little problems
i cant find custom object name and i have to put it in whitelist props can you tell a way to whitelist props by hash or a website to find the name of hash?
and how can i change the resource name cuz hackers can see name and they will stop it if they can
thank you

**Comment by OLucasPk** [comment]
Hey dude, you can find the objects hashes in this site https://mwojtasik.dev/tools/gtav/objects/ and about rename the resource, i think you can do this successfully without any errors.

**Comment by zoomlordir** [comment]
i mean i have the hash and i want the name i need name to put it in whitelist porps

**Comment by OLucasPk** [comment]
Ah, ok, try using this site, it's with the radio example https://forge.plebmasters.de/objects/?d=eyJzZWFyY2giOiItMTk2NDQwMjQzMiIsInBhZ2UiOjEsImZpbHRlciI6eyJ0YWdzIjp7fSwiZGxjIjpbXSwic2l6ZSI6W10sImNhdGVnb3J5IjowfSwiY2F0ZWdvcnkiOjB9

**Comment by zoomlordir** [comment]
i cant find it -434007626

**Comment by OLucasPk** [comment]
If you can't find it you can change the code from **server/main.lua line 676** to **table.insert(WhitelistedPropList,v)** and put the native **GetHashKey("NAMEOFTHEPROP")** in the current props that are in the list and when you need to add a specific hash , just put in the list without the **GetHashKey**. I don't know if it was very clear to understand, anything just call.

**Comment by OLucasPk** [comment]
Lie this 
![image](https://user-images.githubusercontent.com/21092825/122389998-e665f000-cf47-11eb-8a78-bd8b7ef4110b.png)
![image](https://user-images.githubusercontent.com/21092825/122390187-17debb80-cf48-11eb-8af0-1b60e9d171b1.png)

**Comment by zoomlordir** [comment]
thank you so much
