### ISSUE TITLE
vbacmenu/adminmenu

### ISSUE THREAD

**Issue by BigOlDoinks** [visibait/VB-AC#8]
Hey I am having issues trying to get the admin menu to appear ingame, I have the ace bypass setup in the server.cfg to my steam hex. But when I get ingame and try to type /vbacmenu or use the INSERT key to open the menu nothing appears. Any help would be greatly appreciated.

**Comment by Blixed** [comment]
Same

**Comment by Blixed** [comment]
it happens when you put like webhooks or do anything other things to config

**Comment by BigOlDoinks** [comment]
I had to uninstall it for now due to it just banning all our players for random nonsense, it was hitting ppl for pedchance, modifying cars, noclipping, freecam. and these are all my best friends whom I know arent cheating. Hopefully these bugs get sorted out since this is the one anticheat+admin menu ive found so far, and we really need a functioning admin menu ingame in our server.

**Comment by Blixed** [comment]
Yea my friends just connected and it banned. Menu was pretty bad because i couldnt open it always. If creator has time and motivation this is prob good ac

**Comment by visibait** [comment]
Download the new version in GitHub, if it still doesn't work, download the dev version in the "dev" github branch
