### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by Blixed** [visibait/VB-AC#9]
Its giving much error and vbacinstall doesnt do anything. Admin menu is not opening!

**Comment by Blixed** [comment]
![image](https://user-images.githubusercontent.com/78931803/116571584-e36d5c80-a913-11eb-8115-8c4911e09a9d.png)

**Comment by visibait** [comment]
Download the new version in GitHub, if it still doesn't work, download the dev version in the "dev" github branch
